name: Update a file with the new Kubernetes version

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to update format: owner/repo"
        required: true
        type: string
      branch:
        description: "Branch to update e.g. main, master, dev"
        required: true
        default: main
        type: string
      file:
        description: "Path to the file to update eg. ./k8s/deployment.yaml"
        required: true
        type: string
      version:
        description: "New version to update the file with"
        required: true
        type: string
      image:
        description: "Image name to update the file with"
        required: true
        type: string
      username:
        description: "GitHub username"
        required: true
        type: string
      kubernetes_apply:
        description: "Apply the changes to the Kubernetes cluster"
        required: false
        default: false
        type: boolean
      runner:
        description: "Runner to use for the job"
        required: false
        default: "ubuntu-latest"
        type: string
    secrets:
      PRIVATE_REPO_KEY:
        description: "Personal Access Token for private repo access"
        required: true

jobs:
  image:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write

    steps:
      - name: Checkout private repository using PAT
        run: |
          git clone https://${{ inputs.username }}:${{ secrets.PRIVATE_REPO_KEY }}@github.com/${{ inputs.repository }}.git repo

      - name: Check if new version is different
        id: check_version
        run: |
          cd repo
          echo "Checking current version in file: ${{ inputs.file }}"
          cat ${{ inputs.file }}
          CURRENT_VERSION=$(grep -oP '(?<=image: ghcr.io/${{ inputs.image }}:)[^\s"]+' ${{ inputs.file }})
          echo "Current version found: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Expected new version: ${{ inputs.version }}"
          if [ "$CURRENT_VERSION" = "${{ inputs.version }}" ]; then
            echo "The new version is the same as the current version. Exiting..."
            exit 0
          fi

      - name: Update Kubernetes deployment file
        if: env.current_version != inputs.version
        run: |
          cd repo
          echo "Updating the file with sed command"
          sed -i "s|ghcr.io/${{ inputs.image }}:[^\"]*|ghcr.io/${{ inputs.image }}:${{ inputs.version }}|" ${{ inputs.file }}
          echo "sed command executed. Displaying the updated file:"
          cat ${{ inputs.file }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ inputs.file }}
          git commit -m "Update deployment image version to ${{ inputs.version }} [skip ci]"
          git push origin HEAD:${{ inputs.branch }}
          
      - name: Apply changes to Kubernetes cluster
        if: env.current_version != inputs.version && inputs.kubernetes_apply == true
        run: |
          echo "Applying changes to the Kubernetes cluster"
          cd repo && kubectl apply -f ${{ inputs.file }}
          echo "Changes applied to the Kubernetes cluster"
